# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yosuke/workspace/DPGMM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yosuke/workspace/DPGMM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yosuke/workspace/DPGMM/CMakeFiles /home/yosuke/workspace/DPGMM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yosuke/workspace/DPGMM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dpgmm

# Build rule for target.
dpgmm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dpgmm
.PHONY : dpgmm

# fast build rule for target.
dpgmm/fast:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/build
.PHONY : dpgmm/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

calc.o: calc.c.o
.PHONY : calc.o

# target to build an object file
calc.c.o:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/calc.c.o
.PHONY : calc.c.o

calc.i: calc.c.i
.PHONY : calc.i

# target to preprocess a source file
calc.c.i:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/calc.c.i
.PHONY : calc.c.i

calc.s: calc.c.s
.PHONY : calc.s

# target to generate assembly for a file
calc.c.s:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/calc.c.s
.PHONY : calc.c.s

dpgmm.o: dpgmm.c.o
.PHONY : dpgmm.o

# target to build an object file
dpgmm.c.o:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/dpgmm.c.o
.PHONY : dpgmm.c.o

dpgmm.i: dpgmm.c.i
.PHONY : dpgmm.i

# target to preprocess a source file
dpgmm.c.i:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/dpgmm.c.i
.PHONY : dpgmm.c.i

dpgmm.s: dpgmm.c.s
.PHONY : dpgmm.s

# target to generate assembly for a file
dpgmm.c.s:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/dpgmm.c.s
.PHONY : dpgmm.c.s

example.o: example.c.o
.PHONY : example.o

# target to build an object file
example.c.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.c.o
.PHONY : example.c.o

example.i: example.c.i
.PHONY : example.i

# target to preprocess a source file
example.c.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.c.i
.PHONY : example.c.i

example.s: example.c.s
.PHONY : example.s

# target to generate assembly for a file
example.c.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.c.s
.PHONY : example.c.s

gaussian_prior.o: gaussian_prior.c.o
.PHONY : gaussian_prior.o

# target to build an object file
gaussian_prior.c.o:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/gaussian_prior.c.o
.PHONY : gaussian_prior.c.o

gaussian_prior.i: gaussian_prior.c.i
.PHONY : gaussian_prior.i

# target to preprocess a source file
gaussian_prior.c.i:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/gaussian_prior.c.i
.PHONY : gaussian_prior.c.i

gaussian_prior.s: gaussian_prior.c.s
.PHONY : gaussian_prior.s

# target to generate assembly for a file
gaussian_prior.c.s:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/gaussian_prior.c.s
.PHONY : gaussian_prior.c.s

gsl.o: gsl.c.o
.PHONY : gsl.o

# target to build an object file
gsl.c.o:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/gsl.c.o
.PHONY : gsl.c.o

gsl.i: gsl.c.i
.PHONY : gsl.i

# target to preprocess a source file
gsl.c.i:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/gsl.c.i
.PHONY : gsl.c.i

gsl.s: gsl.c.s
.PHONY : gsl.s

# target to generate assembly for a file
gsl.c.s:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/gsl.c.s
.PHONY : gsl.c.s

student_t.o: student_t.c.o
.PHONY : student_t.o

# target to build an object file
student_t.c.o:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/student_t.c.o
.PHONY : student_t.c.o

student_t.i: student_t.c.i
.PHONY : student_t.i

# target to preprocess a source file
student_t.c.i:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/student_t.c.i
.PHONY : student_t.c.i

student_t.s: student_t.c.s
.PHONY : student_t.s

# target to generate assembly for a file
student_t.c.s:
	$(MAKE) -f CMakeFiles/dpgmm.dir/build.make CMakeFiles/dpgmm.dir/student_t.c.s
.PHONY : student_t.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... dpgmm"
	@echo "... edit_cache"
	@echo "... example"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... calc.o"
	@echo "... calc.i"
	@echo "... calc.s"
	@echo "... dpgmm.o"
	@echo "... dpgmm.i"
	@echo "... dpgmm.s"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... gaussian_prior.o"
	@echo "... gaussian_prior.i"
	@echo "... gaussian_prior.s"
	@echo "... gsl.o"
	@echo "... gsl.i"
	@echo "... gsl.s"
	@echo "... student_t.o"
	@echo "... student_t.i"
	@echo "... student_t.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

